kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - export TAG='registry.smilexx.ru/${DRONE_REPO}:${DRONE_COMMIT_SHA:0:8}'
      - export TAG_LATEST='registry.smilexx.ru/${DRONE_REPO}:latest'
      - while (! docker stats --no-stream ); do sleep 1; done
      - DOCKER_BUILDKIT=1 docker build -t $${TAG} . --target production
      - docker push $${TAG}
      - docker tag $${TAG} $${TAG_LATEST}
      - docker push $${TAG_LATEST}

  - name: deploy
    image: curlimages/curl
    pull: if-not-exists
    commands:
      - curl --location --fail --request POST 'https://docker.smilexx.ru/api/stacks/webhooks/4a632103-14ea-4b94-b36e-4ecfeb13c103'


services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - main