version: "3"

services:
  app:
    build: 
      context: .
      target: development
    restart: always
    command: ['npm', 'run', 'start:dev']
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
      - ./views:/usr/src/app/views
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9004:9004

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=bot
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U bot -d bot'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
