version: "3"

services:
  app:
    build: .
    container_name: app
    environment:
      - APP_URL=https://${DNS_DOMAIN}
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgres://bot:bot@postgres:5432/bot
      - LOG_LEVEL=${LOG_LEVEL}
      - PORT=${PORT}
    networks:
      - proxy
      - bot
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.notify-bot.tls.certresolver=lets-encrypt'
      - 'traefik.http.routers.notify-bot.rule=Host(`${DNS_DOMAIN}`) && PathPrefix(`/bot${BOT_TOKEN}`)'
      - 'traefik.http.routers.notify-bot.entrypoints=websecure'
      - 'traefik.http.routers.notify-bot.service=notify-bot'
      - 'traefik.http.services.notify-bot.loadbalancer.server.port=${PORT}'
      - 'traefik.http.services.notify-bot.loadbalancer.server.url=http://app:${PORT}/'

  db:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=bot
    networks:
      - bot
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  
networks:
  bot:
  proxy:
    external: true